const plugins=[
 {id:'colleague-skill',name:'Colleague Skill',owner:'titanwings',description:'将冰冷的离别化为温暖的 Skill，欢迎加入数字生命 1.0。',category:'skills',stars:21956,icon:'✦',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:titanwings/colleague-skill',repo:'https://github.com/titanwings/colleague-skill'},
 {id:'archify',name:'Archify',owner:'tt-a1i',description:'生成漂亮、可验证的架构图、工作流图、时序图和数据流图。',category:'skills',stars:12419,icon:'⌬',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:tt-a1i/archify',repo:'https://github.com/tt-a1i/archify'},
 {id:'vibe-skills',name:'Vibe-Skills',owner:'foryourhealth111-pixel',description:'自动路由本地 Skills，并智能编排 Harness 工作流。',category:'skills',stars:2737,icon:'✳',tone:'lime',updated:'2026-08-14',command:'dsh plugin --profile web add github:foryourhealth111-pixel/Vibe-Skills',repo:'https://github.com/foryourhealth111-pixel/Vibe-Skills'},
 {id:'helloagents',name:'HelloAgents',owner:'hellowind777',description:'自主的高级智能伙伴，持续工作直到完成实现与验证。',category:'skills',stars:677,icon:'✺',tone:'peach',updated:'2026-08-14',command:'dsh plugin --profile web add github:hellowind777/helloagents',repo:'https://github.com/hellowind777/helloagents'},
 {id:'harmony-next-skills',name:'Harmony NEXT Skills',owner:'linhay',description:'覆盖 HarmonyOS NEXT 开发、架构、性能与自动化测试的专家技能。',category:'skills',stars:315,icon:'◇',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:linhay/harmony-next.skills',repo:'https://github.com/linhay/harmony-next.skills'},
 {id:'claude-paper',name:'Claude Paper',owner:'alaliqing',description:'跨 Agent 的论文研究工具包：摘要、深度学习材料、代码 Demo 与本地阅读器。',category:'skills',stars:294,icon:'▱',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:alaliqing/claude-paper',repo:'https://github.com/alaliqing/claude-paper'},
 {id:'openbiliclaw',name:'OpenBiliClaw',owner:'whiteguo233',description:'本地私有的跨平台 AI 内容发现 Agent，支持多个内容平台与 DeepSeek Harness。',category:'tools',stars:2339,icon:'◉',tone:'peach',updated:'2026-08-14',command:'dsh plugin --profile web add github:whiteguo233/OpenBiliClaw',repo:'https://github.com/whiteguo233/OpenBiliClaw'},
 {id:'dsh-tui',name:'DSH TUI',owner:'ccch1mneyyy',description:'全屏终端交互插件，支持流式思考、上下文进度与 TPS 仪表。',category:'tools',stars:839,icon:'▤',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:ccch1mneyyy/dsh-TUI',repo:'https://github.com/ccch1mneyyy/dsh-TUI'},
 {id:'coding-tools-mcp',name:'Coding Tools MCP',owner:'xyTom',description:'让 DeepSeek Harness 获得更完整的编码工具与 MCP 能力。',category:'tools',stars:762,icon:'⌘',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:xyTom/coding-tools-mcp',repo:'https://github.com/xyTom/coding-tools-mcp'},
 {id:'modsearch',name:'ModSearch',owner:'liustack',description:'给纯文本模型补上 web 与 X 搜索能力，输出结构化证据。',category:'tools',stars:86,icon:'⌕',tone:'lime',updated:'2026-08-14',command:'dsh plugin --profile web add github:liustack/modsearch',repo:'https://github.com/liustack/modsearch'},
 {id:'dsh-browser',name:'DSH Browser',owner:'Lum1104',description:'Chrome 侧边栏插件，让 DSH 直接操作浏览器，无需视觉模型。',category:'tools',stars:82,icon:'⌁',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:Lum1104/dsh-browser',repo:'https://github.com/Lum1104/dsh-browser'},
 {id:'dsh-visualize',name:'DSH Visualize',owner:'Nagi-ovo',description:'在 DSH 对话中生成交互式可视化卡片。',category:'tools',stars:81,icon:'◫',tone:'peach',updated:'2026-08-14',command:'dsh plugin --profile web add github:Nagi-ovo/dsh-visualize',repo:'https://github.com/Nagi-ovo/dsh-visualize'},
 {id:'dsh-at-file',name:'DSH @file',owner:'omdsh-dev',description:'像 Codex 一样在 composer 中搜索工作区文件并附加到 prompt。',category:'tools',stars:118,icon:'@',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:omdsh-dev/dsh-at-file',repo:'https://github.com/omdsh-dev/dsh-at-file'},
 {id:'dsh-genui',name:'DSH GenUI',owner:'omdsh-dev',description:'在回复中渲染图表、表单、Mermaid、3D 场景等交互 UI。',category:'tools',stars:72,icon:'▦',tone:'lime',updated:'2026-08-14',command:'dsh plugin --profile web add github:omdsh-dev/dsh-genui',repo:'https://github.com/omdsh-dev/dsh-genui'},
 {id:'modlens',name:'ModLens',owner:'liustack',description:'为纯文本模型提供视觉能力：OCR、布局和语义结构化。',category:'model-adapters',stars:1218,icon:'◎',tone:'lime',updated:'2026-08-14',command:'dsh plugin --profile web add github:liustack/modlens',repo:'https://github.com/liustack/modlens'},
 {id:'agent-vision-toolkit',name:'Agent Vision Toolkit',owner:'Anionex',description:'多图理解、长截图 OCR、UI 还原与 GUI 自动化视觉工具箱。',category:'model-adapters',stars:812,icon:'◉',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:Anionex/agent-vision-toolkit',repo:'https://github.com/Anionex/agent-vision-toolkit'},
 {id:'dsh-vision-toolkit',name:'DSH Vision Toolkit',owner:'Anionex',description:'DeepSeek Harness 原生视觉桥接，支持 OCR、UI 还原、pixel diff 与 Artifacts。',category:'model-adapters',stars:309,icon:'◌',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:Anionex/dsh-vision-toolkit',repo:'https://github.com/Anionex/dsh-vision-toolkit'},
 {id:'deeptide',name:'Deeptide',owner:'paean-ai',description:'Built by DeepSeek, for DeepSeek — Swift-native macOS coding agent.',category:'model-adapters',stars:1048,icon:'⌁',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:paean-ai/deeptide',repo:'https://github.com/paean-ai/deeptide'},
 {id:'ipollowork',name:'iPolloWork',owner:'Devin-AXIS',description:'可自我进化的 AI workspace，连接代码、设计、演示和视频。',category:'enterprise',stars:3915,icon:'◈',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:Devin-AXIS/iPolloWork',repo:'https://github.com/Devin-AXIS/iPolloWork'},
 {id:'mobius',name:'Mobius',owner:'nutshellai-tech',description:'连接团队、AI agents、设备和算力的自我进化 Agent OS。',category:'enterprise',stars:943,icon:'∞',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:nutshellai-tech/mobius',repo:'https://github.com/nutshellai-tech/mobius'},
 {id:'deepseek-harness-desktop',name:'DeepSeek Harness Desktop',owner:'anywhere-labs',description:'为 DeepSeek Harness 生态打造的现代化桌面端体验。',category:'enterprise',stars:1309,icon:'▣',tone:'peach',updated:'2026-08-14',command:'dsh plugin --profile web add github:anywhere-labs/deepseek-harness-desktop',repo:'https://github.com/anywhere-labs/deepseek-harness-desktop'},
 {id:'open-managed-agents',name:'Open Managed Agents',owner:'openma-ai',description:'开源托管 Agent runtime，可运行在 Cloudflare Workers、Durable Objects 或 Node.js。',category:'enterprise',stars:235,icon:'⬢',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:openma-ai/open-managed-agents',repo:'https://github.com/openma-ai/open-managed-agents'},
 {id:'dsh-better-sidebar',name:'DSH Better Sidebar',owner:'omdsh-dev',description:'完整工作台：文件渲染、编辑、终端、Git 与子代理。',category:'productivity',stars:712,icon:'☷',tone:'lime',updated:'2026-08-14',command:'dsh plugin --profile web add github:omdsh-dev/DSH-better-sidebar',repo:'https://github.com/omdsh-dev/DSH-better-sidebar'},
 {id:'mnemon',name:'mnemon',owner:'mnemon-dev',description:'基于图谱的持久记忆，支持跨会话知识召回与 Agent 工作流。',category:'productivity',stars:430,icon:'◌',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:mnemon-dev/mnemon',repo:'https://github.com/mnemon-dev/mnemon'},
 {id:'rea',name:'Rea',owner:'morluto',description:'从应用行为到原生二进制的 Agent 反向工程工具。',category:'productivity',stars:308,icon:'⌁',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:morluto/rea',repo:'https://github.com/morluto/rea'},
 {id:'dsh-handbook',name:'DSH Handbook',owner:'Electricitysheep',description:'DeepSeek Harness 从 0 到 1 的安装、插件开发、调优与实测手册。',category:'productivity',stars:181,icon:'▱',tone:'peach',updated:'2026-08-14',command:'dsh plugin --profile web add github:Electricitysheep/dsh-handbook',repo:'https://github.com/Electricitysheep/dsh-handbook'},
 {id:'sandbase-harness',name:'sandbase-harness',owner:'sandbaseai',description:'带沙箱会话、审计回放和 MCP 工具的 Agent runtime。',category:'devops',stars:574,icon:'⬡',tone:'peach',updated:'2026-08-14',command:'dsh plugin --profile web add github:sandbaseai/sandbase-harness',repo:'https://github.com/sandbaseai/sandbase-harness'},
 {id:'axern',name:'Axern',owner:'cofy-x',description:'面向 AI agents 的开源沙箱、非信任代码执行与持久服务。',category:'devops',stars:275,icon:'◇',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:cofy-x/axern',repo:'https://github.com/cofy-x/axern'},
 {id:'open-record-replay',name:'Open Record Replay',owner:'humblebanana',description:'macOS 录制与回放工作流，捕获鼠标、键盘和 UI 事件轨迹。',category:'devops',stars:136,icon:'◍',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:humblebanana/open-record-replay',repo:'https://github.com/humblebanana/open-record-replay'},
 {id:'dsh-launcher',name:'DSH Launcher',owner:'Ruler4396',description:'轻量 Windows 启动器：静默自启与最小 WebView2 窗口。',category:'devops',stars:70,icon:'↗',tone:'lime',updated:'2026-08-14',command:'dsh plugin --profile web add github:Ruler4396/dsh-launcher',repo:'https://github.com/Ruler4396/dsh-launcher'},
 {id:'dsh-web-ui',name:'DSH Web UI',owner:'zhu1090093659',description:'插件与主题集合：任务板、Git graph、宠物、Token stats。',category:'themes',stars:1800,icon:'▦',tone:'pink',updated:'2026-08-14',command:'dsh plugin --profile web add github:zhu1090093659/dsh-web-ui',repo:'https://github.com/zhu1090093659/dsh-web-ui'},
 {id:'deepseek-harness-desktop-ui',name:'DSH Deep Whale',owner:'Small-tailqwq',description:'DSH Web UI 深海女仆工坊皮肤系列，CC BY-NC-SA 4.0。',category:'themes',stars:540,icon:'◒',tone:'blue',updated:'2026-08-14',command:'dsh plugin --profile web add github:Small-tailqwq/dsh-deep-whale',repo:'https://github.com/Small-tailqwq/dsh-deep-whale'},
 {id:'dsh-ads',name:'DSH Ads',owner:'Nagi-ovo',description:'把 DSH 变成 2005 年门户网站的趣味 UI 主题与互动组件。',category:'themes',stars:323,icon:'✹',tone:'peach',updated:'2026-08-14',command:'dsh plugin --profile web add github:Nagi-ovo/dsh-ads',repo:'https://github.com/Nagi-ovo/dsh-ads'},
 {id:'whale-girl',name:'Whale Girl',owner:'vlln',description:'DSH Web GUI 桌面宠物：悬浮、拖拽、投喂与互动。',category:'themes',stars:120,icon:'◒',tone:'lav',updated:'2026-08-14',command:'dsh plugin --profile web add github:vlln/whale-girl',repo:'https://github.com/vlln/whale-girl'},
 {id:'petdex',name:'Petdex',owner:'crafter-station',description:'面向 DSH 与其他 Agent 的动画宠物公共画廊。',category:'themes',stars:3779,icon:'✦',tone:'lime',updated:'2026-08-14',command:'dsh plugin --profile web add github:crafter-station/petdex',repo:'https://github.com/crafter-station/petdex'}
];
const state={category:'all',search:'',sort:'stars'};const grid=document.querySelector('#plugin-grid');const count=document.querySelector('#result-count');
function formatStars(n){return n>=1000?(n/1000).toFixed(n>=10000?1:1)+'k':n}
function filtered(){let arr=plugins.filter(p=>(state.category==='all'||p.category===state.category)&&(`${p.name} ${p.owner} ${p.description}`.toLowerCase().includes(state.search.toLowerCase())));return arr.sort((a,b)=>state.sort==='name'?a.name.localeCompare(b.name):state.sort==='new'?b.updated.localeCompare(a.updated):b.stars-a.stars)}
function card(p){return `<article class="plugin-card" data-id="${p.id}"><div class="card-top"><span class="icon-box ${p.tone}">${p.icon}</span><span class="card-stars"><span>★</span> ${formatStars(p.stars)}</span></div><h3>${p.name}</h3><p>${p.description}</p><div class="card-bottom"><span class="tag">${p.category}</span><span class="card-arrow">↗</span></div></article>`}
function render(){const arr=filtered();grid.innerHTML=arr.map(card).join('');count.textContent=`${arr.length} plugin${arr.length===1?'':'s'}`;document.querySelector('#empty-state').hidden=arr.length>0;grid.querySelectorAll('.plugin-card').forEach(c=>c.addEventListener('click',()=>openModal(plugins.find(p=>p.id===c.dataset.id))))}
function renderRanking(){document.querySelector('#ranking-list').innerHTML=[...plugins].sort((a,b)=>b.stars-a.stars).slice(0,5).map((p,i)=>`<div class="rank-row"><span class="rank-number">0${i+1}</span><span class="rank-name">${p.name}</span><span class="rank-owner">${p.owner}</span><span class="rank-stars"><span>★</span> ${formatStars(p.stars)}</span><span class="rank-arrow">↗</span></div>`).join('')}
function openModal(p){document.querySelector('#modal-category').textContent=p.category;document.querySelector('#modal-stars').innerHTML=`★ ${p.stars.toLocaleString()} GitHub stars`;document.querySelector('#modal-title').textContent=p.name;document.querySelector('#modal-description').textContent=p.description;document.querySelector('#install-command').textContent=p.command;document.querySelector('#modal-github').href=p.repo;document.querySelector('#modal-updated').textContent=`updated ${p.updated}`;document.querySelector('#modal-image').style.backgroundImage=`url(https://opengraph.githubassets.com/1/${p.owner}/${p.id})`;document.querySelector('#modal-backdrop').hidden=false;document.body.style.overflow='hidden'}
function closeModal(){document.querySelector('#modal-backdrop').hidden=true;document.body.style.overflow=''}
document.querySelector('#categories').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.category=b.dataset.category;document.querySelectorAll('.category').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelector('#search').addEventListener('input',e=>{state.search=e.target.value;render()});document.querySelector('#sort').addEventListener('change',e=>{state.sort=e.target.value;render()});document.querySelector('#clear-search').addEventListener('click',()=>{state.search='';document.querySelector('#search').value='';state.category='all';document.querySelectorAll('.category').forEach(x=>x.classList.toggle('active',x.dataset.category==='all'));render()});document.querySelector('#modal-close').addEventListener('click',closeModal);document.querySelector('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});document.querySelector('#copy-command').addEventListener('click',async()=>{await navigator.clipboard.writeText(document.querySelector('#install-command').textContent);const b=document.querySelector('#copy-command');b.innerHTML='已复制 ✓';setTimeout(()=>b.innerHTML='复制 <span>⧉</span>',1500)});render();renderRanking();
