const enDescriptions={
 'colleague-skill':'A warm, reflective skill for the Digital Life 1.0 community.',archify:'Generate beautiful, verifiable architecture, workflow, sequence and data-flow diagrams.',
 'vibe-skills':'Automatically route local skills and intelligently orchestrate harness workflows.',helloagents:'An autonomous agent partner that keeps working until implementation and verification are complete.','harmony-next-skills':'Expert skills for HarmonyOS NEXT development, architecture, performance and testing.', 'claude-paper':'A cross-agent research toolkit with paper summaries, study material, demos and a local viewer.',
 openbiliclaw:'A private, cross-platform content discovery agent for Bilibili, Xiaohongshu, YouTube and more.','dsh-tui':'A full-screen terminal UI with streaming thoughts, context progress and TPS metrics.','coding-tools-mcp':'Adds a fuller coding-tool and MCP capability set to DeepSeek Harness.',modsearch:'A web and X search bridge that returns structured evidence for text-only models.','dsh-browser':'A Chrome sidebar plugin that lets DSH operate the browser without a vision model.','dsh-visualize':'Generate interactive visualizations inside DSH conversations.','dsh-at-file':'Codex-style workspace file search and prompt attachments in the composer.','dsh-genui':'Render charts, forms, Mermaid, 3D scenes and interactive UI in assistant replies.',
 modlens:'Vision for text-only models: OCR, layout understanding and structured semantics.','agent-vision-toolkit':'A vision toolkit for multi-image Q&A, long screenshots, UI restoration and GUI automation.','dsh-vision-toolkit':'A native DSH vision bridge with OCR, UI restoration, pixel diff and Artifacts.',deeptide:'Built by DeepSeek, for DeepSeek — a Swift-native macOS coding agent.',
 ipollowork:'A self-evolving AI workspace for code, design, presentations and video.',mobius:'A self-evolving Agent OS connecting teams, agents, devices and compute.','deepseek-harness-desktop':'A modern desktop experience for the DeepSeek Harness ecosystem.','open-managed-agents':'An open managed-agent runtime for Cloudflare Workers, Durable Objects or Node.js.',
 'dsh-better-sidebar':'A complete workspace for files, editing, terminal, Git and subagents.',mnemon:'Graph-based persistent memory for cross-session knowledge recall and agent workflows.',rea:'Agent-assisted reverse engineering from app behavior to native binaries.','dsh-handbook':'A practical DeepSeek Harness handbook covering setup, plugin development, tuning and benchmarks.',
 'sandbase-harness':'An agent runtime with sandboxed sessions, audit replay and MCP tools.',axern:'Open sandboxes for AI agents, untrusted code execution and durable services.','open-record-replay':'A macOS workflow recorder that captures mouse, keyboard and UI event traces.','dsh-launcher':'A lightweight Windows launcher with silent startup and a minimal WebView2 window.',
 'dsh-web-ui':'A plugin and theme collection with task boards, Git graphs, pets and token stats.','deepseek-harness-desktop-ui':'A deep-sea maid-workshop skin series for the DSH Web UI.','dsh-ads':'A playful 2005-style portal theme with ads, games and interactive UI.', 'whale-girl':'A draggable desktop pet for the DSH Web GUI.',petdex:'An animated pet gallery for DSH and other agent runtimes.'
};
const ui={zh:{heroTitle:'找到合适的<br /><em>插件</em>来完成工作。',hero:'全网最全的 DeepSeek Harness 插件聚合网站，快速找到你需要的工具。',topic:'主题仓库',categories:'精选分类',stars:'社区星标',snapshot:'最新快照',search:'搜索插件或关键词…',searchLabel:'搜索插件',all:'全部',plugin:'插件',sortStars:'按星标排序',sortName:'按名称排序',sortNew:'最近更新',empty:'没有找到匹配的插件。',clear:'清除筛选',ranking:'Most loved this week',rankingDescription:'按 GitHub stars 排列<br />的社区热度。',install:'安装命令',copy:'复制',copied:'已复制 ✓',github:'查看 GitHub',updated:'更新于',submit:'有好的插件？<br /><em>让更多人发现它。</em>',submitButton:'在 GitHub 上提交',footer:'DeepSeek Harness 独立插件目录',close:'关闭',zhLabel:'中文简介',enLabel:'English summary',readmeLabel:'README 摘要',readmeLink:'README'},en:{heroTitle:'Find the right<br /><em>plugin</em> for the job.',hero:'The most comprehensive DeepSeek Harness plugin directory — find the tools you need, fast.',topic:'topic repositories',categories:'curated categories',stars:'community stars',snapshot:'latest snapshot',search:'Search plugins or keywords…',searchLabel:'Search plugins',all:'All',plugin:'plugin',sortStars:'Sort by stars',sortName:'Sort by name',sortNew:'Recently updated',empty:'No matching plugins found.',clear:'Clear filters',ranking:'Most loved this week',rankingDescription:'Ranked by GitHub stars<br />and community momentum.',install:'INSTALL COMMAND',copy:'Copy',copied:'Copied ✓',github:'View GitHub',updated:'updated',submit:'Built a plugin?<br /><em>Help more people find it.</em>',submitButton:'Submit on GitHub',footer:'Independent directory for DeepSeek Harness',close:'Close',zhLabel:'Chinese overview',enLabel:'English summary',readmeLabel:'README excerpt',readmeLink:'README'}};
const categoryLabels={zh:{skills:'技能',tools:'工具','model-adapters':'模型适配',enterprise:'企业',productivity:'生产力',devops:'DevOps',themes:'主题'},en:{skills:'skills',tools:'tools','model-adapters':'model-adapters',enterprise:'enterprise',productivity:'productivity',devops:'devops',themes:'themes'}};
const state={category:'all',search:'',sort:'stars',lang:'zh',activePlugin:null};const grid=document.querySelector('#plugin-grid');const count=document.querySelector('#result-count');
function t(key){return ui[state.lang][key]}
function formatStars(n){return n>=1000?(n/1000).toFixed(1)+'k':n}
function descriptionFor(p){return state.lang==='en'?(p.descriptionEn||enDescriptions[p.id]||p.description):p.description}
function categoryLabel(category){return category==='all'?t('all'):categoryLabels[state.lang][category]}
function filtered(){let arr=plugins.filter(p=>(state.category==='all'||p.category===state.category)&&(`${p.name} ${p.owner} ${p.description} ${enDescriptions[p.id]||''}`.toLowerCase().includes(state.search.toLowerCase())));return arr.sort((a,b)=>state.sort==='name'?a.name.localeCompare(b.name):state.sort==='new'?b.updated.localeCompare(a.updated):b.stars-a.stars)}
function card(p){return `<article class="plugin-card" data-id="${p.id}"><div class="card-top"><span class="icon-box ${p.tone}">${p.icon}</span><span class="card-stars"><span>★</span> ${formatStars(p.stars)}</span></div><h3>${p.name}</h3><p>${descriptionFor(p)}</p><div class="card-bottom"><span class="tag">${categoryLabel(p.category)}</span><span class="card-arrow">↗</span></div></article>`}
function render(){const arr=filtered();grid.innerHTML=arr.map(card).join('');count.textContent=state.lang==='zh'?`${arr.length} 个${t('plugin')}`:`${arr.length} ${t('plugin')}${arr.length===1?'':'s'}`;document.querySelector('#empty-state').hidden=arr.length>0;grid.querySelectorAll('.plugin-card').forEach(c=>c.addEventListener('click',()=>openModal(plugins.find(p=>p.id===c.dataset.id))))}
function renderRanking(){document.querySelector('#ranking-list').innerHTML=[...plugins].sort((a,b)=>b.stars-a.stars).slice(0,5).map((p,i)=>`<div class="rank-row"><span class="rank-number">0${i+1}</span><span class="rank-name">${p.name}</span><span class="rank-owner">${p.owner}</span><span class="rank-stars"><span>★</span> ${formatStars(p.stars)}</span><span class="rank-arrow">↗</span></div>`).join('')}
function openModal(p){state.activePlugin=p;document.querySelector('#modal-category').textContent=categoryLabel(p.category);document.querySelector('#modal-stars').textContent=`★ ${p.stars.toLocaleString()} GitHub stars`;document.querySelector('#modal-forks').textContent=`${p.forks||0} forks`;document.querySelector('#modal-title').textContent=p.name;document.querySelector('#modal-description').textContent=p.description||'';document.querySelector('#modal-description-en').textContent=p.descriptionEn||enDescriptions[p.id]||p.description||'';document.querySelector('#modal-readme-excerpt').textContent=p.readmeExcerpt||p.descriptionEn||p.description||'';document.querySelector('#modal-zh-label').textContent=t('zhLabel');document.querySelector('#modal-en-label').textContent=t('enLabel');document.querySelector('#modal-readme-label').textContent=t('readmeLabel');document.querySelector('#modal-readme-link').textContent=`${t('readmeLink')} ↗`;document.querySelector('#modal-readme-link').href=p.readme||`${p.repo}#readme`;document.querySelector('#install-label').textContent=t('install');document.querySelector('#install-command').textContent=p.command;document.querySelector('#copy-command').innerHTML=`${t('copy')} <span>⧉</span>`;document.querySelector('#modal-github').textContent=`${t('github')} ↗`;document.querySelector('#modal-github').href=p.repo;document.querySelector('#modal-updated').textContent=`${t('updated')} ${p.updated}`;document.querySelector('#modal-close').setAttribute('aria-label',t('close'));document.querySelector('#modal-image').style.backgroundImage=`url(https://opengraph.githubassets.com/1/${p.owner}/${p.name})`;document.querySelector('#modal-backdrop').hidden=false;document.body.style.overflow='hidden'}
function applyLanguage(){const lang=state.lang;document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelector('#hero-title').innerHTML=t('heroTitle');document.querySelector('#hero-intro').innerHTML=t('hero');document.querySelector('#stats-topic').textContent=t('topic');document.querySelector('#stats-categories').textContent=t('categories');document.querySelector('#stats-snapshot').textContent=t('snapshot');document.querySelector('#search').placeholder=t('search');document.querySelector('#search').setAttribute('aria-label',t('searchLabel'));document.querySelectorAll('.lang-button').forEach(button=>{const active=button.dataset.lang===lang;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});document.querySelectorAll('.category').forEach(b=>{const key=b.dataset.category;b.innerHTML=`${categoryLabel(key)} <b>${key==='all'?plugins.length:plugins.filter(p=>p.category===key).length}</b>`});document.querySelector('#sort').setAttribute('aria-label',lang==='zh'?'排序':'Sort');document.querySelector('#sort option[value="stars"]').textContent=t('sortStars');document.querySelector('#sort option[value="name"]').textContent=t('sortName');document.querySelector('#sort option[value="new"]').textContent=t('sortNew');document.querySelector('#empty-copy').textContent=t('empty');document.querySelector('#clear-search').textContent=t('clear');document.querySelector('#ranking-title').textContent=t('ranking');document.querySelector('#ranking-description').innerHTML=t('rankingDescription');document.querySelector('#submit-title').innerHTML=t('submit');document.querySelector('#submit-button').innerHTML=`${t('submitButton')} <span>↗</span>`;document.querySelector('#footer-description').textContent=t('footer');if(state.activePlugin)openModal(state.activePlugin);render();renderRanking()}
function closeModal(){document.querySelector('#modal-backdrop').hidden=true;document.body.style.overflow='';state.activePlugin=null}
document.querySelector('#categories').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;state.category=b.dataset.category;document.querySelectorAll('.category').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelector('#search').addEventListener('input',e=>{state.search=e.target.value;render()});document.querySelector('#sort').addEventListener('change',e=>{state.sort=e.target.value;render()});document.querySelector('#clear-search').addEventListener('click',()=>{state.search='';document.querySelector('#search').value='';state.category='all';document.querySelectorAll('.category').forEach(x=>x.classList.toggle('active',x.dataset.category==='all'));render()});document.querySelectorAll('.lang-button').forEach(button=>button.addEventListener('click',()=>{state.lang=button.dataset.lang;applyLanguage()}));document.querySelector('#modal-close').addEventListener('click',closeModal);document.querySelector('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});document.querySelector('#copy-command').addEventListener('click',async()=>{await navigator.clipboard.writeText(document.querySelector('#install-command').textContent);const b=document.querySelector('#copy-command');b.innerHTML=`${t('copied')}`;setTimeout(()=>b.innerHTML=`${t('copy')} <span>⧉</span>`,1500)});applyLanguage();
